package com.eme.model.entity.enums;

public enum Error {
    Role_Error,
    Status_Error,
    VersionId_Error,
    UserUsername_Error,
    UserPassword_Error,
    FirstName_Error,
    LastName_Error,
    Phone_Error,
    Email_Error,
    GitHub_Error,
    Telegram_Error,
    Linkedin_Error,
    Instagram_Error,
    MyBirthday_Error,
    MyJob_Error,
    ShortAboutMe_Error,
    CompleteAboutMe_Error,
    BookTitle_Error,
    BookName_Error,
    BookWriter_Error,
    BookExplanation_Error,
    BookGoogleLink_Error,
    ProjectName_Error,
    ProjectProgress_Error,
    ProjectTitle_Error,
    ProjectExplanation_Error
}
